version: '2'

services:

  redis:
    image: redis:4.0.14-alpine
    ports:
      - "6379:6379"
    command:
      redis-server --appendonly yes --requirepass 123456
    volumes:
      - ./not_git/redis:/data